nodes:
  instances:
   # - count: 1
   #   region: us-east-1
   # - count: 1
   #   region: us-east-2
   # - count: 1
   #   region: us-east-1-bos-1a
   # - count: 1
   #   region: us-east-1-iah-1a
   # - count: 1
   #   region: us-east-1-mia-1a
   # - count: 1
   #   region: us-west-1
   # - count: 1
   #   region: af-south-1
   # - count: 1
   #   region: ap-east-1
   # - count: 1
   #   region: ap-south-1
   # - count: 1
   #   region: ap-northeast-3
   # - count: 1
   #   region: ap-northeast-2
   # - count: 1
   #   region: ap-southeast-1
   # - count: 1
   #   region: ap-southeast-2
   # - count: 1
   #   region: ap-northeast-1
    - count: 1
      name: bench_one
      region: ca-central-1
    - count: 1
      name: bench_two
      region: eu-central-1
    #- count: 1
    #  region: eu-west-1
    #- count: 1
    #  region: eu-west-2
    #- count: 1
    #  region: eu-south-1
    #- count: 1
    #  region: eu-west-3
    #- count: 1
    #  region: eu-north-1
    #- count: 1
    #  region: me-south-1
    #- count: 1
    #  region: sa-east-1
  instance: m4.large
