nodes:
  instances:
    - count: 2
      name: merica_ohohio
      region: us-east-2

    - count: 3
      name: merica_caly
      region: us-east-2

    - count: 3
      name: merica_oregon
      region: us-west-2

    - count: 3
      name: asia_mumbai
      region: ap-south-1

    - count: 2
      name: asia_osaka
      region: ap-northeast-3

    - count: 3
      name: asia_seoul
      region: ap-northeast-2

    - count: 4
      name: eu_paris
      region: eu-west-3


  instanceType: t2.large

# command to start the IPFS node
RunCmd: "docker run -d --name ipfs-node -p 4001:4001 -p 5001:5001 -p 8080:8080 ipfs/go-ipfs:latest daemon --migrate=true --routing=dhtclient"
